const sites = [

/* =========================
   SEARCH & CORE INTERNET
========================= */
{name:"Google",url:"https://google.com",category:"Search",score:100},
{name:"YouTube",url:"https://youtube.com",category:"Media",score:99},
{name:"Wikipedia",url:"https://wikipedia.org",category:"Learning",score:98},
{name:"Bing",url:"https://bing.com",category:"Search",score:97},
{name:"DuckDuckGo",url:"https://duckduckgo.com",category:"Search",score:97},
{name:"Yahoo",url:"https://yahoo.com",category:"Search",score:95},
{name:"Brave Search",url:"https://search.brave.com",category:"Search",score:94},
{name:"Startpage",url:"https://startpage.com",category:"Search",score:93},
{name:"Ecosia",url:"https://ecosia.org",category:"Search",score:92},
{name:"WolframAlpha",url:"https://wolframalpha.com",category:"Learning",score:92},

/* =========================
   SOCIAL / COMMUNICATION
========================= */
{name:"Facebook",url:"https://facebook.com",category:"Social",score:98},
{name:"Instagram",url:"https://instagram.com",category:"Social",score:97},
{name:"X",url:"https://x.com",category:"Social",score:96},
{name:"Reddit",url:"https://reddit.com",category:"Social",score:96},
{name:"LinkedIn",url:"https://linkedin.com",category:"Work",score:95},
{name:"TikTok",url:"https://tiktok.com",category:"Social",score:94},
{name:"Pinterest",url:"https://pinterest.com",category:"Social",score:92},
{name:"Discord",url:"https://discord.com",category:"Social",score:92},
{name:"Snapchat",url:"https://snapchat.com",category:"Social",score:91},
{name:"Threads",url:"https://threads.net",category:"Social",score:90},

{name:"WhatsApp Web",url:"https://web.whatsapp.com",category:"Communication",score:95},
{name:"Telegram",url:"https://web.telegram.org",category:"Communication",score:94},
{name:"Gmail",url:"https://mail.google.com",category:"Communication",score:94},
{name:"Outlook",url:"https://outlook.live.com",category:"Communication",score:93},
{name:"Zoom",url:"https://zoom.us",category:"Work",score:92},
{name:"Slack",url:"https://slack.com",category:"Work",score:92},
{name:"Microsoft Teams",url:"https://teams.microsoft.com",category:"Work",score:91},
{name:"Google Meet",url:"https://meet.google.com",category:"Work",score:91},
{name:"Signal",url:"https://signal.org",category:"Communication",score:88},
{name:"Skype",url:"https://skype.com",category:"Communication",score:88},

/* =========================
   AI (TOP)
========================= */
{name:"ChatGPT",url:"https://chat.openai.com",category:"AI",score:100},
{name:"Claude",url:"https://claude.ai",category:"AI",score:98},
{name:"Gemini",url:"https://gemini.google.com",category:"AI",score:97},
{name:"Perplexity",url:"https://perplexity.ai",category:"AI",score:96},
{name:"HuggingFace",url:"https://huggingface.co",category:"AI",score:95},
{name:"Poe",url:"https://poe.com",category:"AI",score:94},
{name:"Midjourney",url:"https://midjourney.com",category:"AI",score:93},
{name:"Leonardo AI",url:"https://leonardo.ai",category:"AI",score:92},
{name:"Runway",url:"https://runwayml.com",category:"AI",score:91},
{name:"Stability AI",url:"https://stability.ai",category:"AI",score:90},

/* =========================
   DEV / PROGRAMMING
========================= */
{name:"GitHub",url:"https://github.com",category:"Dev",score:98},
{name:"GitLab",url:"https://gitlab.com",category:"Dev",score:94},
{name:"StackOverflow",url:"https://stackoverflow.com",category:"Dev",score:95},
{name:"MDN Docs",url:"https://developer.mozilla.org",category:"Dev",score:94},
{name:"Dev.to",url:"https://dev.to",category:"Dev",score:92},
{name:"Hashnode",url:"https://hashnode.com",category:"Dev",score:90},
{name:"CodePen",url:"https://codepen.io",category:"Dev",score:90},
{name:"Replit",url:"https://replit.com",category:"Dev",score:89},
{name:"JSFiddle",url:"https://jsfiddle.net",category:"Dev",score:88},
{name:"Glitch",url:"https://glitch.com",category:"Dev",score:87},
{name:"Docker Hub",url:"https://hub.docker.com",category:"Dev",score:88},
{name:"NPM",url:"https://npmjs.com",category:"Dev",score:88},
{name:"PyPI",url:"https://pypi.org",category:"Dev",score:88},
{name:"Can I Use",url:"https://caniuse.com",category:"Dev",score:87},
{name:"Regex101",url:"https://regex101.com",category:"Dev",score:86},
{name:"JSONLint",url:"https://jsonlint.com",category:"Dev",score:85},

/* =========================
   CLOUD / HOSTING
========================= */
{name:"AWS",url:"https://aws.amazon.com",category:"Cloud",score:95},
{name:"Google Cloud",url:"https://cloud.google.com",category:"Cloud",score:94},
{name:"Azure",url:"https://azure.microsoft.com",category:"Cloud",score:93},
{name:"Vercel",url:"https://vercel.com",category:"Cloud",score:92},
{name:"Netlify",url:"https://netlify.com",category:"Cloud",score:91},
{name:"DigitalOcean",url:"https://digitalocean.com",category:"Cloud",score:90},
{name:"Cloudflare",url:"https://cloudflare.com",category:"Cloud",score:90},
{name:"Render",url:"https://render.com",category:"Cloud",score:88},
{name:"Railway",url:"https://railway.app",category:"Cloud",score:87},
{name:"Heroku",url:"https://heroku.com",category:"Cloud",score:86},

/* =========================
   LEARNING
========================= */
{name:"Coursera",url:"https://coursera.org",category:"Learning",score:93},
{name:"Udemy",url:"https://udemy.com",category:"Learning",score:92},
{name:"edX",url:"https://edx.org",category:"Learning",score:90},
{name:"Khan Academy",url:"https://khanacademy.org",category:"Learning",score:90},
{name:"MIT OCW",url:"https://ocw.mit.edu",category:"Learning",score:88},
{name:"freeCodeCamp",url:"https://freecodecamp.org",category:"Learning",score:88},
{name:"Codecademy",url:"https://codecademy.com",category:"Learning",score:87},
{name:"Brilliant",url:"https://brilliant.org",category:"Learning",score:87},
{name:"Udacity",url:"https://udacity.com",category:"Learning",score:86},
{name:"FutureLearn",url:"https://futurelearn.com",category:"Learning",score:85},

/* =========================
   DESIGN / CREATIVE
========================= */
{name:"Canva",url:"https://canva.com",category:"Design",score:94},
{name:"Figma",url:"https://figma.com",category:"Design",score:93},
{name:"Dribbble",url:"https://dribbble.com",category:"Design",score:90},
{name:"Behance",url:"https://behance.net",category:"Design",score:89},
{name:"Adobe",url:"https://adobe.com",category:"Design",score:89},
{name:"Unsplash",url:"https://unsplash.com",category:"Design",score:88},
{name:"Pexels",url:"https://pexels.com",category:"Design",score:87},
{name:"Pixabay",url:"https://pixabay.com",category:"Design",score:87},
{name:"Coolors",url:"https://coolors.co",category:"Design",score:85},
{name:"FontAwesome",url:"https://fontawesome.com",category:"Design",score:84},

/* =========================
   FINANCE
========================= */
{name:"PayPal",url:"https://paypal.com",category:"Finance",score:92},
{name:"Wise",url:"https://wise.com",category:"Finance",score:91},
{name:"TradingView",url:"https://tradingview.com",category:"Finance",score:90},
{name:"CoinMarketCap",url:"https://coinmarketcap.com",category:"Finance",score:89},
{name:"Coinbase",url:"https://coinbase.com",category:"Finance",score:88},
{name:"Binance",url:"https://binance.com",category:"Finance",score:88},
{name:"Kraken",url:"https://kraken.com",category:"Finance",score:87},
{name:"Investing",url:"https://investing.com",category:"Finance",score:86},
{name:"Yahoo Finance",url:"https://finance.yahoo.com",category:"Finance",score:86},
{name:"XE Currency",url:"https://xe.com",category:"Finance",score:85},

/* =========================
   SHOPPING + MEDIA
========================= */
{name:"Amazon",url:"https://amazon.com",category:"Shopping",score:95},
{name:"eBay",url:"https://ebay.com",category:"Shopping",score:93},
{name:"AliExpress",url:"https://aliexpress.com",category:"Shopping",score:92},
{name:"Walmart",url:"https://walmart.com",category:"Shopping",score:90},
{name:"Etsy",url:"https://etsy.com",category:"Shopping",score:89},
{name:"BestBuy",url:"https://bestbuy.com",category:"Shopping",score:88},
{name:"Newegg",url:"https://newegg.com",category:"Shopping",score:87},
{name:"Target",url:"https://target.com",category:"Shopping",score:87},
{name:"Alibaba",url:"https://alibaba.com",category:"Shopping",score:85},

{name:"Netflix",url:"https://netflix.com",category:"Media",score:94},
{name:"Spotify",url:"https://spotify.com",category:"Media",score:93},
{name:"Twitch",url:"https://twitch.tv",category:"Media",score:92},
{name:"IMDb",url:"https://imdb.com",category:"Media",score:90},
{name:"SoundCloud",url:"https://soundcloud.com",category:"Media",score:89},
{name:"Vimeo",url:"https://vimeo.com",category:"Media",score:88},
  {name:"Disney+",url:"https://disneyplus.com",category:"Media",score:88},
{name:"Prime Video",url:"https://primevideo.com",category:"Media",score:87},
{name:"Crunchyroll",url:"https://crunchyroll.com",category:"Media",score:86},
{name:"RottenTomatoes",url:"https://rottentomatoes.com",category:"Media",score:85},

/* =========================
   PRODUCTIVITY / TOOLS
========================= */
{name:"Notion",url:"https://notion.so",category:"Tools",score:94},
{name:"Trello",url:"https://trello.com",category:"Tools",score:90},
{name:"Google Drive",url:"https://drive.google.com",category:"Tools",score:92},
{name:"Dropbox",url:"https://dropbox.com",category:"Tools",score:90},
{name:"OneDrive",url:"https://onedrive.live.com",category:"Tools",score:89},
{name:"Bitly",url:"https://bitly.com",category:"Tools",score:86},
{name:"TinyURL",url:"https://tinyurl.com",category:"Tools",score:85},
{name:"Speedtest",url:"https://speedtest.net",category:"Tools",score:84},
{name:"Pastebin",url:"https://pastebin.com",category:"Tools",score:83},
{name:"Archive.org",url:"https://archive.org",category:"Tools",score:83},

/* =========================
   SECURITY
========================= */
{name:"VirusTotal",url:"https://virustotal.com",category:"Security",score:90},
{name:"HaveIBeenPwned",url:"https://haveibeenpwned.com",category:"Security",score:89},
{name:"Shodan",url:"https://shodan.io",category:"Security",score:88},
{name:"AbuseIPDB",url:"https://abuseipdb.com",category:"Security",score:87},
{name:"OWASP",url:"https://owasp.org",category:"Security",score:86},
{name:"Nmap",url:"https://nmap.org",category:"Security",score:86},
{name:"Wireshark",url:"https://wireshark.org",category:"Security",score:85},
{name:"Exploit DB",url:"https://exploit-db.com",category:"Security",score:84},
{name:"Kali Linux",url:"https://kali.org",category:"Security",score:84},
{name:"Metasploit",url:"https://metasploit.com",category:"Security",score:83},

/* =========================
   REAL EXTRA (to reach 500)
========================= */
{name:"Product Hunt",url:"https://producthunt.com",category:"Tools",score:82},
{name:"Hacker News",url:"https://news.ycombinator.com",category:"Dev",score:82},
{name:"Arxiv",url:"https://arxiv.org",category:"Learning",score:82},
{name:"Overleaf",url:"https://overleaf.com",category:"Learning",score:81},
{name:"Google Maps",url:"https://maps.google.com",category:"Tools",score:81},
{name:"OpenWeather",url:"https://openweathermap.org",category:"Tools",score:80},
{name:"Fiverr",url:"https://fiverr.com",category:"Work",score:80},
{name:"Upwork",url:"https://upwork.com",category:"Work",score:79},
{name:"Stripe",url:"https://stripe.com",category:"Finance",score:79},
{name:"Shopify",url:"https://shopify.com",category:"Work",score:79},

{name:"Asana",url:"https://asana.com",category:"Work",score:78},
{name:"Monday",url:"https://monday.com",category:"Work",score:78},
{name:"Airtable",url:"https://airtable.com",category:"Work",score:78},
{name:"Zapier",url:"https://zapier.com",category:"Tools",score:77},
{name:"IFTTT",url:"https://ifttt.com",category:"Tools",score:77},
{name:"Obsidian",url:"https://obsidian.md",category:"Tools",score:77},
{name:"Evernote",url:"https://evernote.com",category:"Tools",score:76},
{name:"ProtonMail",url:"https://proton.me",category:"Security",score:76},
{name:"ProtonVPN",url:"https://protonvpn.com",category:"Security",score:76},
{name:"Mullvad",url:"https://mullvad.net",category:"Security",score:75},

{name:"NordVPN",url:"https://nordvpn.com",category:"Security",score:75},
{name:"Bitwarden",url:"https://bitwarden.com",category:"Security",score:75},
{name:"1Password",url:"https://1password.com",category:"Security",score:74},
{name:"Steam",url:"https://store.steampowered.com",category:"Media",score:74},
{name:"Epic Games",url:"https://epicgames.com",category:"Media",score:73},
{name:"GOG",url:"https://gog.com",category:"Media",score:72},
{name:"Unity",url:"https://unity.com",category:"Dev",score:72},
{name:"Unreal Engine",url:"https://unrealengine.com",category:"Dev",score:72},
{name:"Kaggle",url:"https://kaggle.com",category:"Learning",score:71},
{name:"Tableau",url:"https://tableau.com",category:"Tools",score:71},

{name:"Power BI",url:"https://powerbi.microsoft.com",category:"Tools",score:71},
{name:"Photopea",url:"https://photopea.com",category:"Design",score:70},
{name:"TinyPNG",url:"https://tinypng.com",category:"Design",score:70},
{name:"RemoveBG",url:"https://remove.bg",category:"Design",score:70},
{name:"ILovePDF",url:"https://ilovepdf.com",category:"Tools",score:70},
{name:"SmallPDF",url:"https://smallpdf.com",category:"Tools",score:69},
{name:"CloudConvert",url:"https://cloudconvert.com",category:"Tools",score:69},
{name:"Fast.com",url:"https://fast.com",category:"Tools",score:69},
{name:"Cursor",url:"https://cursor.sh",category:"AI",score:82},
{name:"Phind",url:"https://phind.com",category:"AI",score:82},
{name:"You.com",url:"https://you.com",category:"AI",score:81},
{name:"Character AI",url:"https://character.ai",category:"AI",score:81},
{name:"Copy.ai",url:"https://copy.ai",category:"AI",score:80},
{name:"Jasper",url:"https://jasper.ai",category:"AI",score:80},
{name:"Synthesia",url:"https://synthesia.io",category:"AI",score:79},
{name:"ElevenLabs",url:"https://elevenlabs.io",category:"AI",score:79},
{name:"DeepL",url:"https://deepl.com",category:"AI",score:78},
{name:"Grammarly",url:"https://grammarly.com",category:"AI",score:78},

{name:"Supabase",url:"https://supabase.com",category:"Dev",score:82},
{name:"Firebase",url:"https://firebase.google.com",category:"Dev",score:82},
{name:"PlanetScale",url:"https://planetscale.com",category:"Dev",score:81},
{name:"MongoDB Atlas",url:"https://mongodb.com/cloud/atlas",category:"Dev",score:81},
{name:"Postman API",url:"https://postman.com",category:"Dev",score:80},
{name:"Insomnia",url:"https://insomnia.rest",category:"Dev",score:80},
{name:"CodeSandbox",url:"https://codesandbox.io",category:"Dev",score:79},
{name:"StackBlitz",url:"https://stackblitz.com",category:"Dev",score:79},
{name:"Deno",url:"https://deno.com",category:"Dev",score:78},
{name:"Rust Playground",url:"https://play.rust-lang.org",category:"Dev",score:78},

{name:"LeetCode",url:"https://leetcode.com",category:"Learning",score:82},
{name:"HackerRank",url:"https://hackerrank.com",category:"Learning",score:81},
{name:"GeeksforGeeks",url:"https://geeksforgeeks.org",category:"Learning",score:80},
{name:"Roadmap.sh",url:"https://roadmap.sh",category:"Learning",score:80},
{name:"Exercism",url:"https://exercism.org",category:"Learning",score:79},
{name:"Scrimba",url:"https://scrimba.com",category:"Learning",score:79},
{name:"Frontend Mentor",url:"https://frontendmentor.io",category:"Learning",score:78},
{name:"Skillshare",url:"https://skillshare.com",category:"Learning",score:78},
{name:"MasterClass",url:"https://masterclass.com",category:"Learning",score:77},
{name:"OpenAI Docs",url:"https://platform.openai.com/docs",category:"Learning",score:77},

{name:"Notion AI",url:"https://notion.so/product/ai",category:"Tools",score:82},
{name:"ClickUp",url:"https://clickup.com",category:"Tools",score:81},
{name:"Todoist",url:"https://todoist.com",category:"Tools",score:80},
{name:"TickTick",url:"https://ticktick.com",category:"Tools",score:80},
{name:"Calendar",url:"https://calendar.google.com",category:"Tools",score:79},
{name:"Miro",url:"https://miro.com",category:"Tools",score:79},
{name:"Lucidchart",url:"https://lucidchart.com",category:"Tools",score:78},
{name:"Whimsical",url:"https://whimsical.com",category:"Tools",score:78},
{name:"Readwise",url:"https://readwise.io",category:"Tools",score:77},
{name:"Simplenote",url:"https://simplenote.com",category:"Tools",score:77},

{name:"PhotoRoom",url:"https://photoroom.com",category:"Design",score:82},
{name:"Framer",url:"https://framer.com",category:"Design",score:81},
{name:"Spline",url:"https://spline.design",category:"Design",score:80},
{name:"LottieFiles",url:"https://lottiefiles.com",category:"Design",score:80},
{name:"Icons8",url:"https://icons8.com",category:"Design",score:79},
{name:"Flaticon",url:"https://flaticon.com",category:"Design",score:79},
{name:"Heroicons",url:"https://heroicons.com",category:"Design",score:78},
{name:"Google Fonts",url:"https://fonts.google.com",category:"Design",score:78},
{name:"DaFont",url:"https://dafont.com",category:"Design",score:77},
{name:"UI8",url:"https://ui8.net",category:"Design",score:77},

{name:"Cloudinary",url:"https://cloudinary.com",category:"Tools",score:81},
{name:"Imgur",url:"https://imgur.com",category:"Media",score:80},
{name:"Giphy",url:"https://giphy.com",category:"Media",score:79},
{name:"Tenor",url:"https://tenor.com",category:"Media",score:78},
{name:"Mixkit",url:"https://mixkit.co",category:"Media",score:78},
{name:"Freepik",url:"https://freepik.com",category:"Design",score:78},
{name:"Envato Elements",url:"https://elements.envato.com",category:"Design",score:77},
{name:"Storyblocks",url:"https://storyblocks.com",category:"Media",score:77},
{name:"ArtStation",url:"https://artstation.com",category:"Design",score:77},
{name:"Sketchfab",url:"https://sketchfab.com",category:"Design",score:76},

{name:"Namecheap",url:"https://namecheap.com",category:"Cloud",score:81},
{name:"GoDaddy",url:"https://godaddy.com",category:"Cloud",score:80},
{name:"Cloudways",url:"https://cloudways.com",category:"Cloud",score:79},
{name:"Linode",url:"https://linode.com",category:"Cloud",score:79},
{name:"OVHcloud",url:"https://ovhcloud.com",category:"Cloud",score:78},
{name:"Hetzner",url:"https://hetzner.com",category:"Cloud",score:78},
{name:"Hostinger",url:"https://hostinger.com",category:"Cloud",score:77},
{name:"Bluehost",url:"https://bluehost.com",category:"Cloud",score:77},
{name:"cPanel",url:"https://cpanel.net",category:"Cloud",score:76},
{name:"Plesk",url:"https://plesk.com",category:"Cloud",score:76},

{name:"HaveIBeenSold",url:"https://haveibeensold.app",category:"Security",score:79},
{name:"IPinfo",url:"https://ipinfo.io",category:"Security",score:78},
{name:"IPLocation",url:"https://iplocation.net",category:"Security",score:78},
{name:"DNSChecker",url:"https://dnschecker.org",category:"Security",score:77},
{name:"SSL Labs",url:"https://ssllabs.com",category:"Security",score:77},
{name:"MXToolbox",url:"https://mxtoolbox.com",category:"Security",score:77},
{name:"URLVoid",url:"https://urlvoid.com",category:"Security",score:76},
{name:"Hybrid Analysis",url:"https://hybrid-analysis.com",category:"Security",score:76},
{name:"AnyRun",url:"https://any.run",category:"Security",score:76},
{name:"SecurityTrails",url:"https://securitytrails.com",category:"Security",score:75},

{name:"Crunchbase",url:"https://crunchbase.com",category:"Work",score:80},
{name:"AngelList",url:"https://wellfound.com",category:"Work",score:79},
{name:"Indeed",url:"https://indeed.com",category:"Work",score:79},
{name:"Glassdoor",url:"https://glassdoor.com",category:"Work",score:78},
{name:"RemoteOK",url:"https://remoteok.com",category:"Work",score:78},
{name:"WeWorkRemotely",url:"https://weworkremotely.com",category:"Work",score:77},
{name:"Toptal",url:"https://toptal.com",category:"Work",score:77},
{name:"PeoplePerHour",url:"https://peopleperhour.com",category:"Work",score:76},
{name:"Freelancer",url:"https://freelancer.com",category:"Work",score:76},
{name:"Behance Jobs",url:"https://behance.net/joblist",category:"Work",score:75,}
{name:"Raycast",url:"https://raycast.com",category:"Tools",score:82},
{name:"Alfred",url:"https://alfredapp.com",category:"Tools",score:81},
{name:"Warp Terminal",url:"https://warp.dev",category:"Dev",score:81},
{name:"Tabnine",url:"https://tabnine.com",category:"AI",score:80},
{name:"Codeium",url:"https://codeium.com",category:"AI",score:80},
{name:"Recraft",url:"https://recraft.ai",category:"AI",score:79},
{name:"Playground AI",url:"https://playgroundai.com",category:"AI",score:79},
{name:"Gamma",url:"https://gamma.app",category:"AI",score:78},
{name:"Tome",url:"https://tome.app",category:"AI",score:78},
{name:"Beautiful.ai",url:"https://beautiful.ai",category:"AI",score:77},

{name:"Linear",url:"https://linear.app",category:"Work",score:82},
{name:"Basecamp",url:"https://basecamp.com",category:"Work",score:81},
{name:"Coda",url:"https://coda.io",category:"Work",score:80},
{name:"Workflowy",url:"https://workflowy.com",category:"Tools",score:80},
{name:"Milanote",url:"https://milanote.com",category:"Tools",score:79},
{name:"Anytype",url:"https://anytype.io",category:"Tools",score:79},
{name:"Roam Research",url:"https://roamresearch.com",category:"Tools",score:78},
{name:"Bear Notes",url:"https://bear.app",category:"Tools",score:78},
{name:"Standard Notes",url:"https://standardnotes.com",category:"Tools",score:77},
{name:"Logseq",url:"https://logseq.com",category:"Tools",score:77},

{name:"Dailymotion",url:"https://dailymotion.com",category:"Media",score:80},
{name:"Rumble",url:"https://rumble.com",category:"Media",score:79},
{name:"Bandcamp",url:"https://bandcamp.com",category:"Media",score:79},
{name:"Mixcloud",url:"https://mixcloud.com",category:"Media",score:78},
{name:"Letterboxd",url:"https://letterboxd.com",category:"Media",score:78},
{name:"Last.fm",url:"https://last.fm",category:"Media",score:77},
{name:"Metacritic",url:"https://metacritic.com",category:"Media",score:77},
{name:"Deezer",url:"https://deezer.com",category:"Media",score:76},
{name:"Tidal",url:"https://tidal.com",category:"Media",score:76},
{name:"Apple Music",url:"https://music.apple.com",category:"Media",score:76},

{name:"Cloud Academy",url:"https://cloudacademy.com",category:"Learning",score:81},
{name:"Pluralsight",url:"https://pluralsight.com",category:"Learning",score:80},
{name:"DataCamp",url:"https://datacamp.com",category:"Learning",score:80},
{name:"SoloLearn",url:"https://sololearn.com",category:"Learning",score:79},
{name:"W3Schools",url:"https://w3schools.com",category:"Learning",score:79},
{name:"OpenClassrooms",url:"https://openclassrooms.com",category:"Learning",score:78},
{name:"Academic Earth",url:"https://academicearth.org",category:"Learning",score:77},
{name:"Project Gutenberg",url:"https://gutenberg.org",category:"Learning",score:77},
{name:"LibriVox",url:"https://librivox.org",category:"Learning",score:76},
{name:"Internet Archive Books",url:"https://archive.org/details/texts",category:"Learning",score:76},

{name:"Drata",url:"https://drata.com",category:"Security",score:79},
{name:"HackerOne",url:"https://hackerone.com",category:"Security",score:79},
{name:"Bugcrowd",url:"https://bugcrowd.com",category:"Security",score:78},
{name:"Censys",url:"https://censys.io",category:"Security",score:78},
{name:"GreyNoise",url:"https://greynoise.io",category:"Security",score:77},
{name:"SecurityScorecard",url:"https://securityscorecard.com",category:"Security",score:77},
{name:"BuiltWith",url:"https://builtwith.com",category:"Security",score:76},
{name:"Urlscan",url:"https://urlscan.io",category:"Security",score:76},
{name:"CRT.sh",url:"https://crt.sh",category:"Security",score:75},
{name:"IntelX",url:"https://intelx.io",category:"Security",score:75},

{name:"Dribbble Hiring",url:"https://dribbble.com/jobs",category:"Work",score:79},
{name:"Contra",url:"https://contra.com",category:"Work",score:78},
{name:"Arc.dev",url:"https://arc.dev",category:"Work",score:78},
{name:"Remote.co",url:"https://remote.co",category:"Work",score:77},
{name:"Jobspresso",url:"https://jobspresso.co",category:"Work",score:77},
{name:"FlexJobs",url:"https://flexjobs.com",category:"Work",score:76},
{name:"Angel.co Jobs",url:"https://angel.co/jobs",category:"Work",score:76},
{name:"Startup Jobs",url:"https://startup.jobs",category:"Work",score:75},
{name:"JS Remotely",url:"https://jsremotely.com",category:"Work",score:75},
{name:"Remotive",url:"https://remotive.com",category:"Work",score:75},

{name:"Unsplash Wallpapers",url:"https://unsplash.com/wallpapers",category:"Design",score:80},
{name:"Humaaans",url:"https://humaaans.com",category:"Design",score:79},
{name:"Blush",url:"https://blush.design",category:"Design",score:79},
{name:"DrawKit",url:"https://drawkit.com",category:"Design",score:78},
{name:"Iconfinder",url:"https://iconfinder.com",category:"Design",score:78},
{name:"Noun Project",url:"https://thenounproject.com",category:"Design",score:77},
{name:"Haikei",url:"https://haikei.app",category:"Design",score:77},
{name:"BGJar",url:"https://bgjar.com",category:"Design",score:76},
{name:"SVG Repo",url:"https://svgrepo.com",category:"Design",score:76},
{name:"Shape Divider",url:"https://shapedivider.app",category:"Design",score:75},

{name:"OpenSea",url:"https://opensea.io",category:"Finance",score:78},
{name:"CoinGecko",url:"https://coingecko.com",category:"Finance",score:78},
{name:"Glassnode",url:"https://glassnode.com",category:"Finance",score:77},
{name:"Messari",url:"https://messari.io",category:"Finance",score:77},
{name:"Trading Economics",url:"https://tradingeconomics.com",category:"Finance",score:76},
{name:"MarketWatch",url:"https://marketwatch.com",category:"Finance",score:76},
{name:"Seeking Alpha",url:"https://seekingalpha.com",category:"Finance",score:75},
{name:"Morningstar",url:"https://morningstar.com",category:"Finance",score:75},
{name:"FRED",url:"https://fred.stlouisfed.org",category:"Finance",score:74},
{name:"Simply Wall St",url:"https://simplywall.st",category:"Finance",score:74},

{name:"Time.is",url:"https://time.is",category:"Tools",score:78},
{name:"WorldTimeBuddy",url:"https://worldtimebuddy.com",category:"Tools",score:78},
{name:"Temp Mail",url:"https://temp-mail.org",category:"Tools",score:77},
{name:"10MinuteMail",url:"https://10minutemail.com",category:"Tools",score:77},
{name:"QR Code Generator",url:"https://qrcode-monkey.com",category:"Tools",score:76},
{name:"Diffchecker",url:"https://diffchecker.com",category:"Tools",score:76},
{name:"JSON Formatter",url:"https://jsonformatter.org",category:"Tools",score:75},
{name:"RapidTables",url:"https://rapidtables.com",category:"Tools",score:75},
{name:"Convertio",url:"https://convertio.co",category:"Tools",score:74},
{name:"TinyWOW",url:"https://tinywow.com",category:"Tools",score:74},
{name:"Allegro",url:"https://allegro.pl",category:"Polish Store",score:100},
{name:"OLX Polska",url:"https://olx.pl",category:"Polish Store",score:97},
{name:"Ceneo",url:"https://ceneo.pl",category:"Polish Store",score:96},
{name:"Empik",url:"https://empik.com",category:"Polish Store",score:95},
{name:"Morele",url:"https://morele.net",category:"Polish Store",score:94},
{name:"Media Expert",url:"https://mediaexpert.pl",category:"Polish Store",score:94},
{name:"RTV Euro AGD",url:"https://euro.com.pl",category:"Polish Store",score:94},
{name:"x-kom",url:"https://x-kom.pl",category:"Polish Store",score:93},
{name:"Media Markt Polska",url:"https://mediamarkt.pl",category:"Polish Store",score:92},
{name:"Komputronik",url:"https://komputronik.pl",category:"Polish Store",score:92},

{name:"Neonet",url:"https://neonet.pl",category:"Polish Store",score:90},
{name:"Avans",url:"https://avans.pl",category:"Polish Store",score:89},
{name:"OleOle",url:"https://oleole.pl",category:"Polish Store",score:89},
{name:"Sferis",url:"https://sferis.pl",category:"Polish Store",score:88},
{name:"Proline",url:"https://proline.pl",category:"Polish Store",score:88},
{name:"Al.to",url:"https://al.to",category:"Polish Store",score:88},
{name:"Nexterio",url:"https://nexterio.pl",category:"Polish Store",score:87},
{name:"Amazon Polska",url:"https://amazon.pl",category:"Polish Store",score:87},
{name:"AliExpress Polska",url:"https://pl.aliexpress.com",category:"Polish Store",score:86},
{name:"Temu Polska",url:"https://temu.com/pl",category:"Polish Store",score:86},

/* ===== FASHION ===== */
{name:"Zalando Polska",url:"https://zalando.pl",category:"Polish Store",score:93},
{name:"Answear",url:"https://answear.com",category:"Polish Store",score:92},
{name:"eObuwie",url:"https://eobuwie.com.pl",category:"Polish Store",score:92},
{name:"Modivo",url:"https://modivo.pl",category:"Polish Store",score:91},
{name:"Reserved",url:"https://reserved.com/pl",category:"Polish Store",score:90},
{name:"House",url:"https://housebrand.com",category:"Polish Store",score:89},
{name:"Cropp",url:"https://cropp.com",category:"Polish Store",score:89},
{name:"Mohito",url:"https://mohito.com",category:"Polish Store",score:88},
{name:"Sinsay",url:"https://sinsay.com",category:"Polish Store",score:88},
{name:"CCC",url:"https://ccc.eu/pl",category:"Polish Store",score:88},

{name:"Deichmann",url:"https://deichmann.com/PL",category:"Polish Store",score:87},
{name:"Sizeer",url:"https://sizeer.com",category:"Polish Store",score:87},
{name:"SneakerStudio",url:"https://sneakerstudio.pl",category:"Polish Store",score:86},
{name:"Born2be",url:"https://born2be.pl",category:"Polish Store",score:86},
{name:"Domodi",url:"https://domodi.pl",category:"Polish Store",score:86},
{name:"Allani",url:"https://allani.pl",category:"Polish Store",score:85},
{name:"Showroom",url:"https://showroom.pl",category:"Polish Store",score:85},
{name:"Moliera2",url:"https://moliera2.com",category:"Polish Store",score:84},
{name:"Pakuten",url:"https://pakuten.pl",category:"Polish Store",score:84},
{name:"Bonprix Polska",url:"https://bonprix.pl",category:"Polish Store",score:84},

/* ===== HOME & FURNITURE ===== */
{name:"IKEA Polska",url:"https://ikea.com/pl/pl",category:"Polish Store",score:93},
{name:"Leroy Merlin",url:"https://leroymerlin.pl",category:"Polish Store",score:92},
{name:"OBI Polska",url:"https://obi.pl",category:"Polish Store",score:90},
{name:"Castorama",url:"https://castorama.pl",category:"Polish Store",score:90},
{name:"Jysk",url:"https://jysk.pl",category:"Polish Store",score:89},
{name:"Agata Meble",url:"https://agatameble.pl",category:"Polish Store",score:88},
{name:"Black Red White",url:"https://brw.pl",category:"Polish Store",score:88},
{name:"Westwing",url:"https://westwing.pl",category:"Polish Store",score:87},
{name:"Home&You",url:"https://home-you.com",category:"Polish Store",score:87},
{name:"Duka",url:"https://duka.com/pl",category:"Polish Store",score:86},

/* ===== BEAUTY ===== */
{name:"Rossmann",url:"https://rossmann.pl",category:"Polish Store",score:93},
{name:"Hebe",url:"https://hebe.pl",category:"Polish Store",score:92},
{name:"Super-Pharm",url:"https://superpharm.pl",category:"Polish Store",score:91},
{name:"Sephora Polska",url:"https://sephora.pl",category:"Polish Store",score:90},
{name:"Douglas Polska",url:"https://douglas.pl",category:"Polish Store",score:90},
{name:"Notino",url:"https://notino.pl",category:"Polish Store",score:89},
{name:"Cocolita",url:"https://cocolita.pl",category:"Polish Store",score:88},
{name:"Mintishop",url:"https://mintishop.pl",category:"Polish Store",score:87},
{name:"Ladymakeup",url:"https://ladymakeup.pl",category:"Polish Store",score:87},
{name:"Topestetic",url:"https://topestetic.pl",category:"Polish Store",score:86},

/* ===== FOOD / DELIVERY ===== */
{name:"Biedronka Home",url:"https://home.biedronka.pl",category:"Polish Store",score:90},
{name:"Frisco",url:"https://frisco.pl",category:"Polish Store",score:89},
{name:"Lisek",url:"https://lisek.app",category:"Polish Store",score:87},
{name:"Auchan",url:"https://auchan.pl",category:"Polish Store",score:88},
{name:"Carrefour",url:"https://carrefour.pl",category:"Polish Store",score:88},
{name:"Lidl Polska",url:"https://lidl.pl",category:"Polish Store",score:88},
{name:"Glovo",url:"https://glovoapp.com/pl",category:"Polish Store",score:89},
{name:"Pyszne",url:"https://pyszne.pl",category:"Polish Store",score:89},
{name:"Uber Eats Polska",url:"https://ubereats.com/pl",category:"Polish Store",score:88},
{name:"Wolt",url:"https://wolt.com/pl",category:"Polish Store",score:88},

/* ===== BOOKS / CULTURE ===== */
{name:"TaniaKsiazka",url:"https://taniaksiazka.pl",category:"Polish Store",score:90},
{name:"Świat Książki",url:"https://swiatksiazki.pl",category:"Polish Store",score:88},
{name:"Bonito",url:"https://bonito.pl",category:"Polish Store",score:88},
{name:"Gandalf",url:"https://gandalf.com.pl",category:"Polish Store",score:87},
{name:"Book24",url:"https://book24.pl",category:"Polish Store",score:86},

/* ===== AUTO ===== */
{name:"OtoMoto",url:"https://otomoto.pl",category:"Polish Store",score:93},
{name:"AutoDoc",url:"https://autodoc.pl",category:"Polish Store",score:90},
{name:"iParts",url:"https://iparts.pl",category:"Polish Store",score:89},
{name:"Inter Cars",url:"https://intercars.com.pl",category:"Polish Store",score:88},
{name:"Motointegrator",url:"https://motointegrator.com",category:"Polish Store",score:87},

/* ===== PET ===== */
{name:"Zooplus",url:"https://zooplus.pl",category:"Polish Store",score:89},
{name:"Kakadu",url:"https://kakadu.pl",category:"Polish Store",score:87},
{name:"Fera",url:"https://fera.pl",category:"Polish Store",score:86},

/* ===== EXTRA POLISH POPULAR ===== */
{name:"Erli",url:"https://erli.pl",category:"Polish Store",score:85},
{name:"Sprzedajemy",url:"https://sprzedajemy.pl",category:"Polish Store",score:85},
{name:"OLX Praca",url:"https://olx.pl/praca",category:"Polish Store",score:84},
{name:"Pepco",url:"https://pepco.pl",category:"Polish Store",score:84},
{name:"HalfPrice",url:"https://halfprice.eu",category:"Polish Store",score:84},
{name:"SMYK",url:"https://smyk.com",category:"Polish Store",score:84},
{name:"5.10.15",url:"https://51015kids.eu",category:"Polish Store",score:83},
{name:"Decathlon Polska",url:"https://decathlon.pl",category:"Polish Store",score:89},
{name:"4F",url:"https://4f.com.pl",category:"Polish Store",score:86},
{name:"Martes Sport",url:"https://martessport.com.pl",category:"Polish Store",score:85},

{name:"RTVMAX",url:"https://rtvmax.pl",category:"Polish Store",score:80},
{name:"Skapiec",url:"https://skapiec.pl",category:"Polish Store",score:82},
{name:"Empik Foto",url:"https://empikfoto.pl",category:"Polish Store",score:82},
{name:"Printu",url:"https://printu.pl",category:"Polish Store",score:81},
{name:"G2A",url:"https://g2a.com",category:"Polish Store",score:82},
{name:"Muve",url:"https://muve.pl",category:"Polish Store",score:81},
{name:"Komputerswiat",url:"https://komputerswiat.pl",category:"Polish Store",score:80},
{name:"Pepita",url:"https://pepita.com/pl",category:"Polish Store",score:80},
{name:"Fabryka Form",url:"https://fabrykaform.pl",category:"Polish Store",score:80},
{name:"Allegro Lokalnie",url:"https://allegrolokalnie.pl",category:"Polish Store",score:86}
 
];
